apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: flask-docker-app
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the Flask application container
  selector:
    matchLabels:
      app: flask-docker-app
  template:
    metadata:
      labels:
        app: flask-docker-app
    spec:
      containers:
      - name: flask-docker-app #The name of the Flask application container
        image: hainguyen1996/flask-docker-app:latest #The Docker image for building the Flask application container
        ports:
        - containerPort: 5000 #The port for the Flask application container