apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: flask-docker-app
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 5000 #Service port
    targetPort: 5000 #The port for the Flask application container